import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from '@/components/Navbar';
import { Separator } from '@/components/ui/separator';
import { cn } from '@/lib/utils';
import ThemeProvider from '@/providers/ThemeProvider';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={cn(inter.className, 'dark')}
        style={{ colorScheme: 'dark' }}>
        <body>
          <ThemeProvider>
            <div className='flex min-h-screen w-full flex-col items-center dark:bg-black'>
              <Navbar />
              <Separator />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
